spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
  jackson:
    default-property-inclusion: non_null

server:
  error:
    include-exception: false
    include-stacktrace: never
    include-message: never
    include-binding-errors: always

