spring:
  datasource:
#    url: jdbc:postgresql://host.docker.internal:49153/postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver